// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	Title       string `json:"title"`
	ID          string `json:"id"`
	Author      string `json:"author"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

type CreateArticle struct {
	Title       string `json:"title"`
	ID          string `json:"id"`
	Author      string `json:"author"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

type UpdateArticle struct {
	Title       string `json:"title"`
	ID          string `json:"id"`
	Author      string `json:"author"`
	Description string `json:"description"`
	Content     string `json:"content"`
}
